# Generated by Django 2.0.6 on 2018-06-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistergroup',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistergroup',
            name='password_repeat',
            field=models.CharField(max_length=50),
        ),
    ]
