# Generated by Django 2.0.6 on 2018-06-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0002_auto_20180629_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistergroup',
            options={'verbose_name': 'MyUser', 'verbose_name_plural': 'A lot of Users'},
        ),
    ]
