# Generated by Django 2.0.6 on 2018-06-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0003_auto_20180630_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_obj', models.FileField(upload_to='media/')),
            ],
        ),
    ]
