# Generated by Django 2.0.6 on 2018-06-30 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authusers',
            name='email',
        ),
        migrations.AddField(
            model_name='authusers',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=58),
            preserve_default=False,
        ),
    ]
